# Generated by Django 2.2.7 on 2019-11-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovesystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Make'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
