# Generated by Django 2.2.7 on 2019-11-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovesystem', '0002_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.CharField(max_length=2000, verbose_name='内容')),
                ('publishtime', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
            ],
            options={
                'verbose_name': '日记',
                'verbose_name_plural': '日记',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
