# Generated by Django 2.2.7 on 2019-11-20 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovesystem', '0003_auto_20191120_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoryname', models.CharField(max_length=50, verbose_name='纪念日名称')),
                ('memorycontent', models.CharField(max_length=2000, verbose_name='纪念日意义')),
                ('memorydate', models.DateField(default=datetime.datetime.today, verbose_name='纪念日时间')),
            ],
            options={
                'verbose_name': '纪念日',
                'verbose_name_plural': '纪念日',
            },
        ),
    ]
