# Generated by Django 2.2.7 on 2019-11-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovesystem', '0004_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoveTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treename', models.CharField(max_length=50, verbose_name='树名')),
                ('watersize', models.IntegerField(default=0, verbose_name='水量')),
                ('growingtime', models.DateTimeField(auto_now=True, verbose_name='种植日期')),
            ],
            options={
                'verbose_name': '爱情树',
                'verbose_name_plural': '爱情树',
            },
        ),
    ]
