# Generated by Django 2.2.7 on 2019-11-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovesystem', '0005_lovetree'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='createdBy',
            field=models.IntegerField(null=True, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='journal',
            name='createdBy',
            field=models.IntegerField(null=True, verbose_name='发布用户'),
        ),
        migrations.AddField(
            model_name='lovetree',
            name='createBy',
            field=models.IntegerField(null=True, verbose_name='创建用户'),
        ),
    ]
