# Generated by Django 2.2.7 on 2019-11-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lovesystem', '0006_auto_20191120_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lovetree',
            old_name='createBy',
            new_name='createdBy',
        ),
    ]
